server.port=8081
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
spring.mvc.format.date=yyyy-MM-dd
#debug=true


spring.security.oauth2.client.registration.google.client-id=1074017756275-jsadvbkbjmsc624ff8kk8poku6k1mb4i.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.github.client-id=3a7e339eb0b31b9ea656
spring.security.oauth2.client.registration.github.client-secret=35c04e11dd337662664fdae695bec6f8cb214ebf

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.jpa.defer-datasource-initialization=true


spring.datasource.url=jdbc:mysql://localhost:3306/sys
spring.datasource.username=root
spring.datasource.password=Ravi@0570
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
